; this is a comment
; note: end of sections are not denoted, so they are not nestable
# this is also a comment line
#[IGNORED_mysection]
 mystr="my company name" 
myint =123
myfloat = 1.2
list_int=[1,    2,3,4,5]
list_dbl=[1.2,   2,3.3,4,5    ]
list_str=["this","is an","x","test"]
; INVALID_mylist=["abc",2,3,4,5]
;INVALID_mystr=abc