; this is a comment
; note: end of sections are not denoted, so they are not nestable
# this is also a comment line
[mysection]
 mystr="my company name" 
myint =123
myfloat = 1.2
mylist_dbl=[1,2,3,4,5.4]
; INVALID_mylist=["abc",2,3,4,5]
;INVALID_mystr=abc