#!/bin/bash
# Author: Kris Gonzalez
# DateCreated: 190110
# Objective: simple bashrc config across all computers
# How to use: include "source /path/to/codefiles/bash_repo" in .bashrc file
# Assumptions: 
#   * screen installed (apt-get install screen)
#   * jupyter installed (pip install jupyter)


# make bash line colorful 
PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# # important settings (imported from another repo, verify if needed)
# export LC_ALL=C # for pip
# PATH="$PATH:/usr/local/cuda-9.0/bin" # enables usage of nvcc (note: not sure if helps)
# PATH="$PATH:()" # kjg190109: not sure what else must be added to path 

# kjg aliases
alias shortbash='export PS1="\[\033[01;32m\]$ \[\033[00m\]"'
alias longbash="export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '"
alias runjupyter="cd /;jupyter notebook" # won't work until jupyter installed
# alias where='echo "bserver,kitti $STY"' # not needed for now

# special screen commands
alias sn="screen -S $arg1"  # new socket
alias sr="screen -r $arg1"  # reattach to socket
alias sl="screen -ls"       # list active socket
#(detach is CTRL+A,C)
#(delete is sr <ScrName>, exit)
