#!/bin/bash
# Author: Kris Gonzalez
# DateCreated: 190110
# Objective: simple bashrc config across all computers
# How to use: include "source /path/to/codefiles/bash_repo" in .bashrc file
# Assumptions: 
#   * screen installed (apt-get install screen)
#   * jupyter installed (pip install jupyter)
#   * repo 'codefiles' is located in user's home folder


# make bash line colorful 
PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '

# # important settings (imported from another repo, verify if needed)
# export LC_ALL=C # for pip
# PATH="$PATH:/usr/local/cuda-9.0/bin" # enables usage of nvcc (note: not sure if helps)
export PYTHONPATH=$PYTHONPATH:/home/kris/codefiles/lib # personal python libraries
export PYTHONPATH=$PYTHONPATH:~/codefiles/lib

# kjg aliases
alias shortbash='export PS1="\[\033[01;32m\]$ \[\033[00m\]"'
alias longbash="export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '"
alias ipython="ipython --nosep"
alias runjupyter="cd /;jupyter notebook" # won't work until jupyter installed
alias python="python3"

# alias where='echo "bserver,kitti $STY"' # not needed for now

# special screen commands
alias sn="screen -S $arg1"  # new socket
alias sr="screen -r $arg1"  # reattach to socket
alias sl="screen -ls"       # list active socket
#(detach is CTRL+A,C)
#(delete is sr <ScrName>, exit)

# ADDME!!!!!!!!!!
cpprun(){
  # show how to give input arguments with bash as well as variables
  echo "building..."
  g++ -std=c++11 $1
  if [ $? -eq 0 ]
    then
      ./a.out
  fi
}
